### ISSUE TITLE
Translate Functional & Nonfunctional Requirements to Markdown

### ISSUE THREAD

**Issue by Keatonan** [FourYards/yard-work-marketplace#13]
Requirements.md is currently formatting the requirements using a png image. We need to translate these requirements to the markdown file.

Estimated Time: 45m
Actual: 45m

**Comment by CodeTriangle** [comment]
Possibly we could do something like:
```markdown
* 1: User authentication
  * 1.1: The system must authenticate all users.
    * 1.1.1: The system must allow users to create an account specifying the following:
    * 1.1.2: The system must allow returning users to log in using their account.
* 2: User profile features
  * 2.1: The system must allow authenticated users to change important aspects of their profile, including:
  * 2.2: The system must allow authenticated users to add or remove Customer and Provider roles from their own profile.
  * 2.3: The system must not allow any user to make modifications to other users' profiles, unless that user is an Owner.
  * 2.4: The system must allow authenticated users to manage funds by:
```

which should render like:
* 1: User authentication
  * 1.1: The system must authenticate all users.
    * 1.1.1: The system must allow users to create an account specifying the following:
    * 1.1.2: The system must allow returning users to log in using their account.
* 2: User profile features
  * 2.1: The system must allow authenticated users to change important aspects of their profile, including:
  * 2.2: The system must allow authenticated users to add or remove Customer and Provider roles from their own profile.
  * 2.3: The system must not allow any user to make modifications to other users' profiles, unless that user is an Owner.
  * 2.4: The system must allow authenticated users to manage funds by:
