### ISSUE TITLE
Use Case Entry & Exit Conditions

### ISSUE THREAD

**Issue by Keatonan** [FourYards/yard-work-marketplace#4]
Need to document the entry and exit conditions for all use case diagrams for clarity. Add a short description of the event flow.

Estimated Time: 80m
Actual: 60m

**Comment by Keatonan** [comment]
I put my use case updates on the entry-exit-conditions branch if you guys want to keep it all in one branch.

**Comment by CodeTriangle** [comment]
I've added mine, should be good to go.

**Comment by Kytech** [comment]
I'll close this after I get mine taken care of
