### ISSUE TITLE
View Listing Details

### ISSUE THREAD

**Issue by WesleyPerrett** [FourYards/yard-work-marketplace#40]
When you click on a listing you have to be able to view the details of the listing and place a bid if you want.

Estimated Time: 180m
Actual: 180m

**Comment by WesleyPerrett** [comment]
Job details page is almost done. Needs "place bid" button wired up. Also needs data for API to work properly.

**Comment by Kytech** [comment]
Leaving opened since API needs to be wired up, but keeping linked to relevant PR(s)

**Comment by CodeTriangle** [comment]
this is pretty much done. closing.
