### ISSUE TITLE
Improve User API

### ISSUE THREAD

**Issue by CodeTriangle** [FourYards/yard-work-marketplace#90]
So the user API currently does like no error checking. Gonna want to add that. 

I want to add error checking to the phone number and stuff.

Critically, password changes do not work. Everything else is optional. This is not.

Estimated Time: 60m
Actual: --

**Comment by Kytech** [comment]
I think with the time we have left and based on recent feedback, we can skip this for the sake of time.

**Comment by CodeTriangle** [comment]
won't fix.
closing.
